server:
  port: ${PORT}
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://${DATABASE_ENDPOINT_URL}:3306/${DATABASE_NAME}?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
#logging:
#  level:
#    org.hibernate.SQL: debug
#aws:
#  credentials:
#    access-key: ${AWS_ACCESS_KEY_ID}
#    secret-key: ${AWS_SECRET_ACCESS_KEY}
#
#  s3:
#    bucket: ${AWS_S3_BUCKET_NAME}
#    region: ${AWS_REGION}